# Generated by Django 3.2.7 on 2026-09-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_auto_20260813_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticketattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='account.employeeticketcomment'),
        ),
    ]
