# Generated by Django 3.2.7 on 2026-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_employeeticketattachment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeticket',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets_many', to='account.EmployeeProfile'),
        ),
    ]
